### ISSUE TITLE
Access Denied for accessing all files

### ISSUE THREAD

**Issue by ChaiBapchya** [d2l-ai/berkeley-stat-157#4]
Are the pdfs - in this github repo's slides and media folder not supposed to be accessible to outside public?

All URLs point to such media give Access Denied error.
Example 1 - 
On the page - https://courses.d2l.ai/berkeley-stat-157/project.html

Pt 2. talks about "Style files are here"
It points to URL - https://courses.d2l.ai/berkeley-stat-157/media/latex.zip

Example 2 -
Similarly, on page - https://courses.d2l.ai/berkeley-stat-157/units/introduction.html
Logistics PDF throws same issue
https://courses.d2l.ai/berkeley-stat-157/units/slides/1_22/1-Logistics.pdf

Does it mean that the URLs are incorrect?
Looks like a minor change in that case.

**Comment by mli** [comment]
should be fixed now

**Comment by mli** [comment]
fixed by https://github.com/d2l-ai/berkeley-stat-157/commit/775ce56ec07185aa5a148a729c3f05c0c6c33c07
